config/routes.rb
Rails.application.routes.draw do
  root to: 'static#home'
  get 'static/home'

  # User routes
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: true

  validates :password, presence: true, length: { minimum: 6 }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      reset_session
      log_in user
      redirect_to user
    else
      flash.now[:danger] = "Invalid email/password combination"
      render :new
    end
  end

  def destroy
    log_out
    flash[:success] = "User has been logged out"
    redirect_to root_url
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Blog App"
      redirect_to @user
    else
      render :new
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    reset_session
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', "data-turbo-track": "reload", media: 'all' %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="d-flex flex-column h-100">
    <%= render "shared/navigation" %>
    <main class="flex-shrink-0" role="main">
      <div class="container my-4">

        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>

        <%= yield %>
      </div>

      <%= debug(params) if Rails.env.development? %>
    </main>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <span class="fw-bolder fs-4">The form contains <%= pluralize(@user.errors.count, "error") %>:</span>
    </div>
    <ul class="mb-2 text-danger">
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer position-absolute bottom-0 w-100 py-2 bg-light">
  <div class="container d-flex justify-content-between align-items-center">
    <small class="text-muted">
      <%= link_to "Chuck Smith", "https://eclecticsaddlebag.com/" %>
    </small>
    <nav class="navbar navbar-expand">
      <ul class="navbar-nav">
        <li class="nav-item"><%= link_to "About", "#", class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Contact", "#", class: "nav-link" %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Blog App", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Help", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <% if logged_in? %>
            <%= link_to "Users", users_path, class: "nav-link" %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Account
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to "Profile", current_user, class: "dropdown-item" %></li>
              <li><%= link_to "Settings", "#", class: "dropdown-item" %></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><%= button_to "Log out", logout_path, method: :delete, data: { turbo: false }, class: "dropdown-item" %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to "Log in", login_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/new.html.erb
<div class="row mt-5">
  <div class="col-md-8 justify-content-md-center mx-auto">
    <h1 class="text-center">Sign up</h1>
    <div class="col-md-6 mx-auto justify-content-md-center">
      <%= form_with(model: @user, local: true) do |f| %>
        <%= render "shared/error_messages" %>

        <div class="mb-3">
          <%= f.label :name, class: "form-label" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :email, class: "form-label" %>
          <%= f.email_field :email, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :password, class: "form-label" %>
          <%= f.password_field :password, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :password_confirmation, "Confirmation", class: "form-label" %>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>

        <%= f.submit "Create my account", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1>User show page</h1>